In [63]:
#Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

In [64]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import *

In [65]:
#Mouting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [66]:
#Importing Data
data=pd.read_csv("/content/drive/MyDrive/customer_churn.csv")
data

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [67]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [68]:
#Null values
data.isnull().sum().sum()

0

In [69]:
#Duplicates
data.duplicated().sum()

0

In [70]:
data['Churn'].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [71]:
data.shape

(7043, 21)

In [72]:
data.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [73]:
data=data.drop(["customerID"],axis=1)
data.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

When converting data types or performing operations, pandas provides several options for error handling:

errors='raise': This is the default setting where errors are raised as exceptions if encountered. This is useful for debugging but can halt your program if not handled properly.

errors='coerce': Converts invalid parsing to NaN (for numeric conversions) or NaT (for datetime conversions). This approach is used when you want to handle invalid data by setting it to a standard missing value.

errors='ignore': Ignores errors and returns the original data without any changes. This is useful when you want to preserve the original data even if some elements can't be converted.

In [74]:
data["TotalCharges"]=pd.to_numeric(data['TotalCharges'], errors='coerce')
data.isnull().sum()

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [75]:
mean_value = data['TotalCharges'].mean() # Calculate the mean of 'TotalCharges', ignoring NaN values
data['TotalCharges'].fillna(mean_value, inplace=True) #Replace NaN values in 'TotalCharges' with the calculated mean
print(data)

      gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0     Female        0          Yes       No        1         No
1       Male        0           No       No       34        Yes
2       Male        0           No       No        2        Yes
3       Male        0           No       No       45         No
4     Female        0           No       No        2        Yes
...      ...            ...     ...        ...     ...          ...
7038    Male        0          Yes      Yes       24        Yes
7039  Female        0          Yes      Yes       72        Yes
7040  Female        0          Yes      Yes       11         No
7041    Male        1          Yes       No        4        Yes
7042    Male        0           No       No       66        Yes

       MultipleLines   InternetService OnlineSecurity OnlineBackup  \
0     No phone service            DSL         No           Yes
1                   No            DSL        Yes            No
2                   No            DSL        Yes           Yes
3     No phone service            DSL        Yes            No
4                   No    Fiber optic         No            No
...                ...             ...            ...          ...
7038               Yes            DSL        Yes            No
7039               Yes    Fiber optic         No           Yes
7040  No phone service            DSL        Yes            No
7041               Yes    Fiber optic         No            No
7042                No    Fiber optic        Yes            No

     DeviceProtection TechSupport StreamingTV StreamingMovies     Contract     \
0            No             No          No            No       Month-to-month
1           Yes             No          No            No             One year
2            No             No          No            No       Month-to-month
3           Yes            Yes          No            No             One year
4            No             No          No            No       Month-to-month
...               ...         ...         ...             ...             ...
7038        Yes            Yes         Yes           Yes             One year
7039        Yes             No         Yes           Yes             One year
7040         No             No          No            No       Month-to-month
7041         No             No          No            No       Month-to-month
7042        Yes            Yes         Yes           Yes             Two year

     PaperlessBilling       PaymentMethod         MonthlyCharges  \
0           Yes                 Electronic check       29.85
1            No                     Mailed check       56.95
2           Yes                     Mailed check       53.85
3            No        Bank transfer (automatic)       42.30
4           Yes                 Electronic check       70.70
...               ...                        ...             ...
7038        Yes                     Mailed check       84.80
7039        Yes          Credit card (automatic)      103.20
7040        Yes                 Electronic check       29.60
7041        Yes                     Mailed check       74.40
7042        Yes        Bank transfer (automatic)      105.65

      TotalCharges Churn
0          29.85      No
1        1889.50      No
2         108.15     Yes
3        1840.75      No
4         151.65     Yes
...            ...   ...
7038     1990.50      No
7039     7362.90      No
7040      346.45      No
7041      306.60     Yes
7042     6844.50      No

[7043 rows x 20 columns]

In [76]:
data.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [77]:
data["SeniorCitizen"]=data["SeniorCitizen"].map({0:"No",1:"Yes"})
data.head

<bound method NDFrame.head of       gender SeniorCitizen Partner Dependents  tenure PhoneService  \
0     Female        No        Yes       No        1         No
1       Male        No         No       No       34        Yes
2       Male        No         No       No        2        Yes
3       Male        No         No       No       45         No
4     Female        No         No       No        2        Yes
...      ...           ...     ...        ...     ...          ...
7038    Male        No        Yes      Yes       24        Yes
7039  Female        No        Yes      Yes       72        Yes
7040  Female        No        Yes      Yes       11         No
7041    Male       Yes        Yes       No        4        Yes
7042    Male        No         No       No       66        Yes

       MultipleLines   InternetService OnlineSecurity OnlineBackup  \
0     No phone service            DSL         No           Yes
1                   No            DSL        Yes            No
2                   No            DSL        Yes           Yes
3     No phone service            DSL        Yes            No
4                   No    Fiber optic         No            No
...                ...             ...            ...          ...
7038               Yes            DSL        Yes            No
7039               Yes    Fiber optic         No           Yes
7040  No phone service            DSL        Yes            No
7041               Yes    Fiber optic         No            No
7042                No    Fiber optic        Yes            No

     DeviceProtection TechSupport StreamingTV StreamingMovies     Contract     \
0            No             No          No            No       Month-to-month
1           Yes             No          No            No             One year
2            No             No          No            No       Month-to-month
3           Yes            Yes          No            No             One year
4            No             No          No            No       Month-to-month
...               ...         ...         ...             ...             ...
7038        Yes            Yes         Yes           Yes             One year
7039        Yes             No         Yes           Yes             One year
7040         No             No          No            No       Month-to-month
7041         No             No          No            No       Month-to-month
7042        Yes            Yes         Yes           Yes             Two year

     PaperlessBilling       PaymentMethod         MonthlyCharges  \
0           Yes                 Electronic check       29.85
1            No                     Mailed check       56.95
2           Yes                     Mailed check       53.85
3            No        Bank transfer (automatic)       42.30
4           Yes                 Electronic check       70.70
...               ...                        ...             ...
7038        Yes                     Mailed check       84.80
7039        Yes          Credit card (automatic)      103.20
7040        Yes                 Electronic check       29.60
7041        Yes                     Mailed check       74.40
7042        Yes        Bank transfer (automatic)      105.65

      TotalCharges Churn
0          29.85      No
1        1889.50      No
2         108.15     Yes
3        1840.75      No
4         151.65     Yes
...            ...   ...
7038     1990.50      No
7039     7362.90      No
7040      346.45      No
7041      306.60     Yes
7042     6844.50      No

[7043 rows x 20 columns]>

In [78]:
#To check the details of my numeric data

In [79]:
numerical_cols=['tenure', 'MonthlyCharges', 'TotalCharges']
data[numerical_cols].describe()

         tenure     MonthlyCharges  TotalCharges
count  7043.000000    7043.000000    7043.000000
mean     32.371149      64.761692    2283.300441
std      24.559481      30.090047    2265.000258
min       0.000000      18.250000      18.800000
25%       9.000000      35.500000     402.225000
50%      29.000000      70.350000    1400.550000
75%      55.000000      89.850000    3786.600000
max      72.000000     118.750000    8684.800000

In [80]:
data.describe(include='O')

,gender,SeniorCitizen,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Churn
count,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043
unique,2,2,2,2,2,3,3,3,3,3,3,3,3,3,2,4,2
top,Male,No,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,No
freq,3555,5901,3641,4933,6361,3390,3096,3498,3088,3095,3473,2810,2785,3875,4171,2365,5174

In [81]:
#Creating Dataframe for correlation plot
data2=data
data["Churn"].replace(to_replace="yes",value=1,inplace=True)
data["Churn"].replace(to_replace="yes",value=1,inplace=True)
data_dummies=pd.get_dummies(data2)
data_dummies.head()

,tenure,MonthlyCharges,TotalCharges,gender_Female,gender_Male,SeniorCitizen_No,SeniorCitizen_Yes,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,PhoneService_No,PhoneService_Yes,MultipleLines_No,MultipleLines_No phone service,MultipleLines_Yes,InternetService_DSL,InternetService_Fiber optic,InternetService_No,OnlineSecurity_No,OnlineSecurity_No internet service,OnlineSecurity_Yes,OnlineBackup_No,OnlineBackup_No internet service,OnlineBackup_Yes,DeviceProtection_No,DeviceProtection_No internet service,DeviceProtection_Yes,TechSupport_No,TechSupport_No internet service,TechSupport_Yes,StreamingTV_No,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn_No,Churn_Yes
0,1,29.85,29.85,True,False,True,False,False,True,True,False,True,False,False,True,False,True,False,False,True,False,False,False,False,True,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,True,False,False,True,False,True,False
1,34,56.95,1889.50,False,True,True,False,True,False,True,False,False,True,True,False,False,True,False,False,False,False,True,True,False,False,False,False,True,True,False,False,True,False,False,True,False,False,False,True,False,True,False,False,False,False,True,True,False
2,2,53.85,108.15,False,True,True,False,True,False,True,False,False,True,True,False,False,True,False,False,False,False,True,False,False,True,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,True,False,False,False,True,False,True
3,45,42.30,1840.75,False,True,True,False,True,False,True,False,True,False,False,True,False,True,False,False,False,False,True,True,False,False,False,False,True,False,False,True,True,False,False,True,False,False,False,True,False,True,False,True,False,False,False,True,False
4,2,70.70,151.65,True,False,True,False,True,False,True,False,False,True,True,False,False,False,True,False,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,True,False,False,True,False,False,True

Visualizing The Data

In [82]:
#Gender Spread and Churn Distribution
data['gender'].value_counts()

gender
Male      3555
Female    3488
Name: count, dtype: int64

In [83]:
!pip install sweetviz

Requirement already satisfied: sweetviz in /usr/local/lib/python3.10/dist-packages (2.3.1)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (2.2.2)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (1.26.4)
Requirement already satisfied: matplotlib>=3.1.3 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (3.8.0)
Requirement already satisfied: tqdm>=4.43.0 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (4.66.6)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (1.13.1)
Requirement already satisfied: jinja2>=2.11.1 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (3.1.4)
Requirement already satisfied: importlib-resources>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (6.4.5)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2>=2.11.1->sweetviz) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (4.54.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (24.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.16.0)

In [84]:
!pip install autoviz

Requirement already satisfied: autoviz in /usr/local/lib/python3.10/dist-packages (0.1.905)
Requirement already satisfied: xlrd in /usr/local/lib/python3.10/dist-packages (from autoviz) (2.0.1)
Requirement already satisfied: wordcloud in /usr/local/lib/python3.10/dist-packages (from autoviz) (1.9.3)
Requirement already satisfied: emoji in /usr/local/lib/python3.10/dist-packages (from autoviz) (2.14.0)
Requirement already satisfied: pyamg in /usr/local/lib/python3.10/dist-packages (from autoviz) (5.2.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from autoviz) (1.5.2)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.10/dist-packages (from autoviz) (0.14.4)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from autoviz) (3.8.1)
Requirement already satisfied: textblob in /usr/local/lib/python3.10/dist-packages (from autoviz) (0.17.1)
Requirement already satisfied: xgboost<1.7,>=0.82 in /usr/local/lib/python3.10/dist-packages (from autoviz) (1.6.2)
Requirement already satisfied: fsspec>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from autoviz) (2024.10.0)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.10/dist-packages (from autoviz) (4.12.2)
Requirement already satisfied: pandas-dq>=1.29 in /usr/local/lib/python3.10/dist-packages (from autoviz) (1.29)
Requirement already satisfied: numpy>=1.24.0 in /usr/local/lib/python3.10/dist-packages (from autoviz) (1.26.4)
Requirement already satisfied: hvplot>=0.9.2 in /usr/local/lib/python3.10/dist-packages (from autoviz) (0.11.1)
Requirement already satisfied: holoviews>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from autoviz) (1.19.1)
Requirement already satisfied: panel>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from autoviz) (1.4.5)
Requirement already satisfied: pandas>=2.0 in /usr/local/lib/python3.10/dist-packages (from autoviz) (2.2.2)
Requirement already satisfied: matplotlib>3.7.4 in /usr/local/lib/python3.10/dist-packages (from autoviz) (3.8.0)
Requirement already satisfied: seaborn>0.12.2 in /usr/local/lib/python3.10/dist-packages (from autoviz) (0.13.2)
Requirement already satisfied: bokeh>=3.1 in /usr/local/lib/python3.10/dist-packages (from holoviews>=1.16.0->autoviz) (3.4.3)
Requirement already satisfied: colorcet in /usr/local/lib/python3.10/dist-packages (from holoviews>=1.16.0->autoviz) (3.1.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from holoviews>=1.16.0->autoviz) (24.1)
Requirement already satisfied: param<3.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from holoviews>=1.16.0->autoviz) (2.1.1)
Requirement already satisfied: pyviz-comms>=2.1 in /usr/local/lib/python3.10/dist-packages (from holoviews>=1.16.0->autoviz) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>3.7.4->autoviz) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>3.7.4->autoviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>3.7.4->autoviz) (4.54.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>3.7.4->autoviz) (1.4.7)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>3.7.4->autoviz) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>3.7.4->autoviz) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>3.7.4->autoviz) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.0->autoviz) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.0->autoviz) (2024.2)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.10/dist-packages (from panel>=1.4.0->autoviz) (2024.9.0)
Requirement already satisfied: markdown in /usr/local/lib/python3.10/dist-packages (from panel>=1.4.0->autoviz) (3.7)
Requirement already satisfied: markdown-it-py in /usr/local/lib/python3.10/dist-packages (from panel>=1.4.0->autoviz) (3.0.0)
Requirement already satisfied: linkify-it-py in /usr/local/lib/python3.10/dist-packages (from panel>=1.4.0->autoviz) (2.0.3)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.10/dist-packages (from panel>=1.4.0->autoviz) (0.4.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from panel>=1.4.0->autoviz) (2.32.3)
Requirement already satisfied: tqdm>=4.48.0 in /usr/local/lib/python3.10/dist-packages (from panel>=1.4.0->autoviz) (4.66.6)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from panel>=1.4.0->autoviz) (6.2.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->autoviz) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->autoviz) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->autoviz) (3.5.0)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->autoviz) (8.1.7)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk->autoviz) (2024.9.11)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.10/dist-packages (from statsmodels->autoviz) (0.5.6)
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.10/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (3.1.4)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.10/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (6.0.2)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.10/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (6.3.3)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.6->statsmodels->autoviz) (1.16.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->panel>=1.4.0->autoviz) (0.5.1)
Requirement already satisfied: uc-micro-py in /usr/local/lib/python3.10/dist-packages (from linkify-it-py->panel>=1.4.0->autoviz) (1.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py->panel>=1.4.0->autoviz) (0.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->panel>=1.4.0->autoviz) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->panel>=1.4.0->autoviz) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->panel>=1.4.0->autoviz) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->panel>=1.4.0->autoviz) (2024.8.30)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from Jinja2>=2.9->bokeh>=3.1->holoviews>=1.16.0->autoviz) (3.0.2)

In [85]:
from autoviz.AutoViz_Class import AutoViz_Class

In [86]:
AV=AutoViz_Class()
report=AV.AutoViz(data)

Shape of your Data Set loaded: (7043, 20)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  2
    Number of Integer-Categorical Columns =  1
    Number of String-Categorical Columns =  10
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  7
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  0
    Number of Columns to Delete =  0
    20 Predictors classified...
        No variables removed since no ID or low-information variables found in data set
To fix these data quality issues in the dataset, import FixDQ from autoviz...
There are 22 duplicate rows in your dataset
    Alert: Dropping duplicate rows can sometimes cause your column data types to change to object!
    All variables classified into correct types.

Number of All Scatter Plots = 3
All Plots done
Time to run AutoViz = 11 seconds

 ###################### AUTO VISUALIZATION Completed ########################

In [87]:
# Defining a Function to Convert Objects to Int
from sklearn.preprocessing import LabelEncoder
def object_to_int(dataframe_series):
    if dataframe_series.dtype == 'object':
        dataframe_series = LabelEncoder().fit_transform(dataframe_series)
    return dataframe_series

In [88]:
data2=data
# Apply the function to convert categorical columns to integers
data = data.apply(lambda x: object_to_int(x))

# Separate features (x) and target (y)
X = data.drop(columns=['Churn'])
y = data["Churn"].values  # Use .values to get a numpy array

# Display the transformed DataFrame
print(data.head())

   gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0     0          0           1          0         1          0
1     1          0           0          0        34          1
2     1          0           0          0         2          1
3     1          0           0          0        45          0
4     0          0           0          0         2          1

   MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0        1               0                0              2
1        0               0                2              0
2        0               0                2              2
3        1               0                2              0
4        0               1                0              0

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0          0              0            0              0             0
1          2              0            0              0             1
2          0              0            0              0             0
3          2              2            0              0             1
4          0              0            0              0             0

   PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn
0          1               2             29.85           29.85      0
1          0               3             56.95         1889.50      0
2          1               3             53.85          108.15      1
3          0               0             42.30         1840.75      0
4          1               2             70.70          151.65      1

In [89]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=99)

In [90]:
num_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']

In [91]:
#rescaling
scaler=StandardScaler()

X_train[num_cols]=scaler.fit_transform(X_train[num_cols])
X_test[num_cols]=scaler.fit_transform(X_test[num_cols])

In [92]:
X_train[num_cols]

       tenure   MonthlyCharges  TotalCharges
5537  1.580139     1.675034       2.546738
7042  1.375649     1.363136       2.026912
1712 -0.137575    -0.309172      -0.290063
3072  1.171160     0.492142       1.129291
4991  1.048466     1.389680       1.717061
...        ...             ...           ...
1768  1.252955    -0.199676       0.545180
1737 -1.037330    -0.674160      -0.869606
3240  0.884874     1.392998       1.547400
5305  0.434996     0.472234       0.526021
4737  1.621037     1.689966       2.678081

[5634 rows x 3 columns]

In [93]:
X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols]

       tenure   MonthlyCharges  TotalCharges
2905 -0.456384     0.457355      -0.250458
6651 -0.136123     0.064039      -0.225005
5321  1.465186     1.367838       2.140571
4293 -0.736613     0.812175      -0.516644
5686 -1.056875     0.656523      -0.788103
...        ...             ...           ...
3874 -0.936777    -0.729286      -0.830591
1196  1.345088     0.659870       1.396913
981   0.304237    -1.537674      -0.655585
173   0.824663     0.981217       1.163363
6870  0.664532     0.303376       0.607924

[1409 rows x 3 columns]

Random Forest Classifier

In [94]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

# Assuming df is your DataFrame and 'Churn' is your target variable
X = data.drop(columns=['Churn'])
y = data['Churn']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=99)

# Initialize the RandomForestClassifier with OOB score
model_rf= RandomForestClassifier(
    n_estimators=1000,
    random_state=65,
    max_leaf_nodes=35)

# Fit the model
model_rf.fit(X_train,y_train)

#make predictions'
y_predict=model_rf.predict(X_test)

# Print accuracy score
print("accuracy_score:",accuracy_score(y_test,y_predict))
print('-' * 60)


# Print classification report
print("confusion_matrix:",confusion_matrix(y_test,y_predict))
print('-' * 60)

accuracy_score: 0.7913413768630234
------------------------------------------------------------
confusion_matrix: [[933  90]
 [204 182]]
------------------------------------------------------------